/**
 * Zero-dependency file export (Blob + anchor download) — no PDF/DOCX
 * library added, keeping bundle size and cost at zero. PDF export is
 * covered separately via the browser's native print-to-PDF, styled by
 * a dedicated @media print stylesheet.
 */
export function downloadTextFile(filename: string, content: string, mimeType = "text/markdown") {
  const blob = new Blob([content], { type: `${mimeType};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

import { ReadinessScorecard, LearnerTimelineMilestone } from "@/lib/ai/memory/MemoryEngine";
import { MistakePattern } from "@/lib/ai/memory/InsightMemory";
import { StudyPlanSuggestion } from "@/lib/ai/memory/StudyPlanEngine";
import { BookmarkEntry } from "@/types/study.types";

export interface StudyReportInput {
  generatedAt: string;
  coachGreeting: string;
  coachBody: string;
  readiness: ReadinessScorecard | null;
  metrics: {
    learningVelocity: number;
    spacedRevisionDebt: number;
    burnoutRisk: string;
    daysToExam: number | null;
  };
  mistakePatterns: MistakePattern[];
  savedShortcuts: BookmarkEntry[];
  studyPlanSuggestions: StudyPlanSuggestion[];
  timeline: LearnerTimelineMilestone[];
  subjectMasteries: { subject: string; masteryIndex: number; averageConfidence: number }[];
}

/**
 * Builds a Markdown study report from real, already-computed AI Mentor
 * state — nothing here is generated by a fresh AI call, and nothing is
 * fabricated: every section reflects exactly what's on screen.
 */
export function buildStudyReportMarkdown(input: StudyReportInput): string {
  const lines: string[] = [];

  lines.push(`# RENYXERA — AI Mentor Study Report`);
  lines.push(``);
  lines.push(`_Generated ${input.generatedAt}_`);
  lines.push(``);
  lines.push(`## Coach Summary`);
  lines.push(``);
  lines.push(`**${input.coachGreeting}**`);
  lines.push(``);
  lines.push(input.coachBody);
  lines.push(``);

  if (input.readiness) {
    const r = input.readiness;
    lines.push(`## Readiness Predictor`);
    lines.push(``);
    lines.push(`| Metric | Value |`);
    lines.push(`|---|---|`);
    lines.push(`| Expected Marks Rank | #${r.expectedRank} |`);
    lines.push(`| Confidence Interval | ${r.confidenceInterval[0]}–${r.confidenceInterval[1]} marks |`);
    lines.push(`| Readiness Rating | ${r.readinessRating} |`);
    lines.push(`| Suggested Mock Date | ${r.suggestedMockDate} |`);
    lines.push(`| Revision Target Date | ${r.revisionCompletionDate} |`);
    lines.push(``);
  }

  lines.push(`## Learning Health Metrics`);
  lines.push(``);
  lines.push(`| Metric | Value |`);
  lines.push(`|---|---|`);
  lines.push(`| Learning Velocity | ${input.metrics.learningVelocity}/100 |`);
  lines.push(`| Spaced Revision Debt | ${input.metrics.spacedRevisionDebt} items |`);
  lines.push(`| Burnout Risk | ${input.metrics.burnoutRisk} |`);
  lines.push(`| Days to Target Exam | ${input.metrics.daysToExam !== null ? input.metrics.daysToExam : "Not set"} |`);
  lines.push(``);

  lines.push(`## Subject Progress & Mastery`);
  lines.push(``);
  if (input.subjectMasteries.length === 0) {
    lines.push(`_No subject performance data recorded yet._`);
  } else {
    lines.push(`| Subject | Mastery Index | Avg. Confidence |`);
    lines.push(`|---|---|---|`);
    input.subjectMasteries
      .slice()
      .sort((a, b) => a.masteryIndex - b.masteryIndex)
      .forEach(s => {
        lines.push(`| ${s.subject} | ${s.masteryIndex}% | ${s.averageConfidence}% |`);
      });
  }
  lines.push(``);

  lines.push(`## Mistake Cognitive Patterns`);
  lines.push(``);
  if (input.mistakePatterns.length === 0) {
    lines.push(`_No structural mistake patterns detected yet._`);
  } else {
    input.mistakePatterns.forEach(p => {
      lines.push(`### ${p.name} (Probability: ${p.probability}%)`);
      lines.push(``);
      lines.push(p.description);
      lines.push(``);
      lines.push(`**Suggested fix:** ${p.suggestedFix}`);
      lines.push(``);
    });
  }

  lines.push(`## AI Study Plan Suggestions`);
  lines.push(``);
  if (input.studyPlanSuggestions.length === 0) {
    lines.push(`_No active suggestions._`);
  } else {
    input.studyPlanSuggestions.forEach(s => {
      lines.push(`- **[${s.priority}] ${s.title}** (${s.suggestedDate}) — ${s.reason}`);
    });
  }
  lines.push(``);

  lines.push(`## Saved Shortcuts & Exam Tricks`);
  lines.push(``);
  if (input.savedShortcuts.length === 0) {
    lines.push(`_No shortcuts saved yet._`);
  } else {
    input.savedShortcuts.forEach(b => {
      lines.push(`### ${b.topic || "Untitled"} (${b.subject || "General"})`);
      lines.push(``);
      lines.push(b.aiShortcut || "_No content._");
      lines.push(``);
    });
  }

  lines.push(`## Learning Timeline`);
  lines.push(``);
  if (input.timeline.length === 0) {
    lines.push(`_No timeline milestones yet._`);
  } else {
    input.timeline.slice(0, 30).forEach(t => {
      lines.push(`- **${new Date(t.timestamp).toLocaleDateString()}** — ${t.title}: ${t.description}`);
    });
  }
  lines.push(``);

  lines.push(`---`);
  lines.push(`_This report reflects locally recorded study data only. AI-generated content is clearly labeled where applicable and is not sourced from official GATE material unless explicitly noted._`);

  return lines.join("\n");
}
