// The official GATE 2027 CS & IT and General Aptitude syllabus, worded as published by the
// organising institute (IIT Madras), mapped to the subjects our question bank uses so each
// section links to its PYQs and shows real past-paper weightage per topic.
export const SYLLABUS_SOURCE = {
  exam: "GATE 2027",
  institute: "IIT Madras",
  cs: "https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/CS_GATE2027_Syllabus.pdf",
  ga: "https://gate2027.iitm.ac.in/static/doc/GATE2027_Syllabus/GA_GATE2027_Syllabus.pdf",
  page: "https://gate2027.iitm.ac.in/exam_papers_and_syllabus",
};

export type SyllabusSection = { title: string; group: "General Aptitude" | "Engineering Mathematics" | "Core CS"; subjects: string[]; topics: string };

export const SYLLABUS: SyllabusSection[] = [
  { title: "General Aptitude", group: "General Aptitude", subjects: ["Verbal Aptitude", "Quantitative Aptitude", "Analytical Aptitude", "Spatial Aptitude"], topics: "Verbal Aptitude — basic English grammar: tenses, articles, adjectives, prepositions, conjunctions, verb-noun agreement, and other parts of speech; basic vocabulary: words, idioms, and phrases in context; reading and comprehension, narrative sequencing. Quantitative Aptitude — data interpretation: data graphs (bar graphs, pie charts, and other graphs representing data), 2- and 3-dimensional plots, maps, and tables; numerical computation and estimation: ratios, percentages, powers, exponents and logarithms, permutations and combinations, and series; mensuration and geometry; elementary statistics and probability. Analytical Aptitude — logic: deduction and induction; analogy; numerical relations and reasoning. Spatial Aptitude — transformation of shapes: translation, rotation, scaling, mirroring, assembling, and grouping; paper folding, cutting, and patterns in 2 and 3 dimensions. 15 marks in every paper." },
  { title: "Discrete Mathematics", group: "Engineering Mathematics", subjects: ["Discrete Mathematics"], topics: "Propositional and first order logic. Sets, relations, functions, partial orders and lattices. Monoids, Groups. Graphs: connectivity, matching, colouring. Combinatorics: counting, recurrence relations, generating functions." },
  { title: "Linear Algebra", group: "Engineering Mathematics", subjects: ["Linear Algebra"], topics: "Matrices, determinants, system of linear equations, eigenvalues and eigenvectors, LU decomposition." },
  { title: "Calculus", group: "Engineering Mathematics", subjects: ["Calculus"], topics: "Limits, continuity and differentiability, Maxima and minima, Mean value theorem, Integration." },
  { title: "Probability and Statistics", group: "Engineering Mathematics", subjects: ["Probability & Statistics"], topics: "Random variables, Uniform, normal, exponential, Poisson and binomial distributions. Mean, median, mode and standard deviation. Conditional probability and Bayes theorem." },
  { title: "Digital Logic", group: "Core CS", subjects: ["Digital Logic"], topics: "Boolean algebra and minimization – algebraic technique, Karnaugh map, tabular method. Design of combinational and sequential circuits. Number representation and arithmetic (fixed and floating point)." },
  { title: "Computer Organization and Architecture", group: "Core CS", subjects: ["Computer Organization and Architecture (COA)"], topics: "Instruction set and addressing modes. Design of arithmetic and logic unit (ALU). Design of control unit – hardwired and microprogrammed. Memory interfacing and hierarchy: performance, cache memory mapping. I/O interface (interrupt and DMA). Instruction pipelining, pipeline hazards." },
  { title: "Programming and Data Structures", group: "Core CS", subjects: ["Programming in C", "Data Structures"], topics: "Programming in C. Recursion. Arrays, stacks, queues, linked lists, trees, binary search trees, binary heaps, graphs." },
  { title: "Algorithms", group: "Core CS", subjects: ["Algorithms"], topics: "Searching, sorting, hashing. Asymptotic worst case time and space complexity. Algorithm design techniques: greedy, dynamic programming and divide-and-conquer. Graph traversals, minimum spanning trees, shortest paths." },
  { title: "Theory of Computation", group: "Core CS", subjects: ["Theory of Computation (TOC)"], topics: "Regular expressions and finite automata. Context-free grammars and push-down automata. Regular and context-free languages, pumping lemma. Turing machines and undecidability." },
  { title: "Compiler Design", group: "Core CS", subjects: ["Compiler Design"], topics: "Lexical analysis, parsing, syntax-directed translation. Runtime environments. Intermediate code generation. Local optimisation, Data flow analyses: constant propagation, liveness analysis, common sub expression elimination." },
  { title: "Operating System", group: "Core CS", subjects: ["Operating Systems (OS)"], topics: "System calls, processes, threads, inter-process communication, concurrency and synchronization. Deadlock. CPU and I/O scheduling. Memory management and virtual memory. File systems." },
  { title: "Databases", group: "Core CS", subjects: ["Database Management Systems (DBMS)"], topics: "ER-model. Relational model: relational algebra, tuple calculus, SQL. Integrity constraints, normal forms. File organization, indexing (e.g., B and B+ trees). Transactions and concurrency control." },
  { title: "Computer Networks", group: "Core CS", subjects: ["Computer Networks (CN)"], topics: "Principles of Layering; Basics of switching (circuit, packet and virtual circuit) and performance metrics; Data link layer: error detection, Medium Access Control, Ethernet; Distance vector and link state routing; IPv4 - Fragmentation, CIDR Notation, Network Address Translation; TCP - flow control and congestion control, socket API; DNS and HTTP." },
];
