// The GATE CS & IT syllabus (unchanged in structure across recent GATE editions), mapped
// to the subjects our question bank uses so each section links to its PYQs and weightage.
export const SYLLABUS: { title: string; subjects: string[]; topics: string }[] = [
  { title: "General Aptitude", subjects: ["Verbal Aptitude", "Quantitative Aptitude", "Analytical Aptitude", "Spatial Aptitude"], topics: "Verbal aptitude (grammar, vocabulary, reading comprehension), quantitative aptitude (data interpretation, arithmetic, numbers, mensuration), analytical aptitude (logic, deduction, induction) and spatial aptitude (transformation of shapes, paper folding, patterns). 15 marks in every paper." },
  { title: "Discrete Mathematics", subjects: ["Discrete Mathematics"], topics: "Propositional and first-order logic. Sets, relations, functions, partial orders and lattices. Monoids, groups. Graphs: connectivity, matching, colouring. Combinatorics: counting, recurrence relations, generating functions." },
  { title: "Linear Algebra", subjects: ["Linear Algebra"], topics: "Matrices, determinants, systems of linear equations, eigenvalues and eigenvectors, LU decomposition." },
  { title: "Calculus", subjects: ["Calculus"], topics: "Limits, continuity and differentiability. Maxima and minima. Mean value theorem. Integration." },
  { title: "Probability and Statistics", subjects: ["Probability & Statistics"], topics: "Random variables. Uniform, normal, exponential, Poisson and binomial distributions. Mean, median, mode and standard deviation. Conditional probability and Bayes' theorem." },
  { title: "Digital Logic", subjects: ["Digital Logic"], topics: "Boolean algebra. Combinational and sequential circuits. Minimisation. Number representations and computer arithmetic (fixed and floating point)." },
  { title: "Computer Organization and Architecture", subjects: ["Computer Organization and Architecture (COA)"], topics: "Machine instructions and addressing modes. ALU, data path and control unit. Instruction pipelining and pipeline hazards. Memory hierarchy: cache, main memory and secondary storage; I/O interface (interrupt and DMA mode)." },
  { title: "Programming and Data Structures", subjects: ["Programming in C", "Data Structures"], topics: "Programming in C. Recursion. Arrays, stacks, queues, linked lists, trees, binary search trees, binary heaps, graphs." },
  { title: "Algorithms", subjects: ["Algorithms"], topics: "Searching, sorting, hashing. Asymptotic worst-case time and space complexity. Algorithm design techniques: greedy, dynamic programming and divide-and-conquer. Graph traversals, minimum spanning trees, shortest paths." },
  { title: "Theory of Computation", subjects: ["Theory of Computation (TOC)"], topics: "Regular expressions and finite automata. Context-free grammars and push-down automata. Regular and context-free languages, pumping lemma. Turing machines and undecidability." },
  { title: "Compiler Design", subjects: ["Compiler Design"], topics: "Lexical analysis, parsing, syntax-directed translation. Runtime environments. Intermediate code generation. Local optimisation; data-flow analyses: constant propagation, liveness analysis, common sub-expression elimination." },
  { title: "Operating System", subjects: ["Operating Systems (OS)"], topics: "System calls, processes, threads, inter-process communication, concurrency and synchronisation. Deadlock. CPU and I/O scheduling. Memory management and virtual memory. File systems." },
  { title: "Databases", subjects: ["Database Management Systems (DBMS)"], topics: "ER model. Relational model: relational algebra, tuple calculus, SQL. Integrity constraints, normal forms. File organisation, indexing (e.g. B and B+ trees). Transactions and concurrency control." },
  { title: "Computer Networks", subjects: ["Computer Networks (CN)"], topics: "Layering: OSI and TCP/IP stacks. Packet, circuit and virtual-circuit switching. Data link layer: framing, error detection, medium access control, Ethernet bridging. Routing: shortest path, flooding, distance vector and link state. Fragmentation and IP addressing, IPv4, CIDR; ARP, DHCP, ICMP; NAT. Transport layer: flow and congestion control, UDP, TCP, sockets. Application layer: DNS, SMTP, HTTP, FTP, email." },
];
