import { initialCalc, press, type CalcState } from "../lib/exam/calculator";

const run = (keys: string[], mode: "deg" | "rad" | "grad" = "deg"): CalcState => keys.reduce((s, k) => press(s, k), initialCalc(mode));
let fails = 0;
const eq = (name: string, got: string, want: string) => { const ok = got === want; if (!ok) fails++; console.log(`${ok ? "PASS" : "FAIL"} ${name}: ${got}${ok ? "" : ` (want ${want})`}`); };

eq("2+3*4=", run([..."2", "+", ..."3", "*", ..."4", "="]).entry, "14");
eq("(2+3)*4=", run(["(", "2", "+", "3", ")", "*", "4", "="]).entry, "20");
eq("2^10=", run(["2", "pow", "1", "0", "="]).entry, "1024");
eq("2^3^2 right-assoc", run(["2", "pow", "3", "pow", "2", "="]).entry, "512");
eq("30 cos (deg)", run(["3", "0", "cos"]).entry, "0.866025403784");
eq("sin 180 deg", run(["1", "8", "0", "sin"]).entry, "0");
eq("cos 90 deg", run(["9", "0", "cos"]).entry, "0");
eq("tan 90 deg error", run(["9", "0", "tan"]).entry, "Error");
eq("sin(pi/2) rad", run(["pi", "/", "2", "=", "sin"], "rad").entry, "1");
eq("asin 0.5 deg", run([".", "5", "asin"]).entry, "30");
eq("log 1000", run(["1", "0", "0", "0", "log"]).entry, "3");
eq("ln e", run(["e", "ln"]).entry, "1");
eq("5 fact", run(["5", "fact"]).entry, "120");
eq("2.5 fact error", run(["2", ".", "5", "fact"]).entry, "Error");
eq("sqrt 144", run(["1", "4", "4", "sqrt"]).entry, "12");
eq("27 cbrt", run(["2", "7", "cbrt"]).entry, "3");
eq("1/8 inv", run(["8", "inv"]).entry, "0.125");
eq("1/0 error", run(["1", "/", "0", "="]).entry, "Error");
eq("0.1+0.2", run(["0", ".", "1", "+", "0", ".", "2", "="]).entry, "0.3");
eq("7 mod 3", run(["7", "mod", "3", "="]).entry, "1");
eq("-7 mod 3", run(["7", "±", "mod", "3", "="]).entry, "2");
eq("8 yroot 3", run(["8", "yroot", "3", "="]).entry, "2");
eq("12 % ", run(["1", "2", "pct"]).entry, "0.12");
eq("sinh 1", run(["1", "sinh"]).entry, "1.17520119364");
eq("exp 2e3", run(["2", "EXP", "3", "+", "1", "="]).entry, "2001");
eq("negate", run(["5", "±", "+", "2", "="]).entry, "-3");
eq("op change", run(["5", "+", "*", "4", "="]).entry, "20");
eq("memory add", run(["5", "MS", "C", "3", "M+", "MR"]).entry, "8");
eq("memory carry", run(["5", "MS", "C", "MR"]).entry, "5");
eq("chain after =", run(["2", "+", "3", "=", "*", "4", "="]).entry, "20");
eq("backspace", run(["1", "2", "3", "⌫"]).entry, "12");
eq("unary inside expr", run(["1", "+", "9", "sqrt", "="]).entry, "4");
eq("large", run(["1", "0", "fact"]).entry, "3628800");
eq("unclosed paren", run(["(", "2", "+", "3", "="]).entry, "5");
eq("grad cos 100", run(["1", "0", "0", "cos"], "grad").entry, "0");
console.log(fails ? `${fails} FAILED` : "all passed");
process.exit(fails ? 1 : 0);
